MSVC/arm64ec: Deassert XSIMD_WITH_SSE2.
The ARM64EC ABI is designed to provide native ARM64 code into emulated x64 applications.
Long blog article about ARM64EC: http://www.emulators.com/docs/abc_arm64ec_explained.htm

For this goal, it *on purpose* needs to define both `_M_AMD64` and `_M_X64`, however it
does not define `__SSE2__`. SSE *should* be supported, but it fails to compile our
constant setting methods:
```
xsimd_sse2.hpp(1479): warning C4003: not enough arguments for function-like macro invocation '_mm_setr_ps'
xsimd_sse2.hpp(1479): error C2760: syntax error: '...' was unexpected here; expected ')'
```

I think this is likely a bug within their intrinsics, however not enabling SSE might still
be better on an emulated platform anyways.