Adding missing header "memory"
Build apache arrow on fedora-33 with clang-11 failed with below xsimd error:

xsimd_ep/src/xsimd_ep-install/include/xsimd/types/../memory/xsimd_aligned_allocator.hpp:345:15:
error: no member named 'allocator' in namespace 'std'; did you mean 'alloca'?
              std::allocator<T>
              ^~~~~